export enum EmployeeRole {
  MANAGER = 'MANAGER',
  CASHIER = 'CASHIER',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  WAREHOUSE_STAFF = 'WAREHOUSE_STAFF',
  SHIPPER = 'SHIPPER',
}

export enum CustomerAddressType {
  OFFICE = 'OFFICE',
  HOME = 'HOME',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPING = 'SHIPPING',
  SHIPPED = 'SHIPPED',
  // COMPLETED = 'COMPLETED',

  // CANCELLED = 'CANCELLED',

  // RETURN_REQUESTED = 'RETURN_REQUESTED',
  // RETURN_REJECTED = 'RETURN_REJECTED',
  // RETURN_ACCEPTED = 'RETURN_ACCEPTED',
  // RETURN_SHIPPING = 'RETURN_SHIPPING',
  // RETURN_COMPLETED = 'RETURN_COMPLETED',
}

export enum PaymentMethod {
  COD = 'COD',
  MoMo = 'MoMo',
  VNPAY = 'VNPAY',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}
