export const DEFAULT_PAGE = 1;

export const DEFAULT_DOCS_PER_PAGE = 10;

export const DEFAULT_HOT_PRODUCTS_LIMIT = 5;
export const DEFAULT_NEW_PRODUCTS_LIMIT = 5;
export const DEFAULT_RELATED_PRODUCTS_LIMIT = 5;
